### ISSUE TITLE
Authorization flow

### ISSUE THREAD

**Issue by tomkersten** [christiansmith/anvil-connect#1]
The following behaviors are present which seem to be out of line with my expectations:

When signing into a client application:

1. If the visitor has already logged into the auth server, the session is not "remembered" forcing them to log in every time.
2. When a visitor has logged out of a client application and attempts to log _back into_ an application they have already authorized, they are prompted with an authorization request every time (vs remembering they had previously authorized the application).
3. Trusted applications are prompting for authorization.

**Comment by christiansmith** [comment]
Closing this for now. Reopen if necessary.
