### ISSUE TITLE
mongodb support

### ISSUE THREAD

**Issue by adrai** [christiansmith/anvil-connect#69]
How far is anvil-connect to support mongodb too?

**Comment by christiansmith** [comment]
Can you share some of the reasons you're thinking of using Mongo?

Theoretically it would be fairly easy to port. However, there is no current plan to do so. We don't believe Mongo is the right choice as the _primary_ database for this project for a variety of reasons (ultimately Redis isn't the final answer either). 

Philosophically, Anvil Connect is not an application. It's a piece of infrastructure that supports applications. In line with that reasoning, Anvil should take responsibility for persistence internally, using an embedded database like lmdb or leveldb. 

The advantage of this approach is that there are no external dependencies. Deployment would be simpler and cheaper. The main disadvantage is that we have to deal with horizontal scalability of persistence in-house as well. For example, implementing dynamo or a similar pattern. This a longer term vision that many will argue is out of reach. I'm personally excited to make a branch and start experimenting as time permits.

Operational persistence aside, the data shouldn't be locked up in Anvil. One feature we've discussed is writing to multiple data stores simultaneously while reading only from the primary one. I can't be certain how difficult this would be in practice until we take a closer look.

Feedback and ideas are appreciated :)

**Comment by adrai** [comment]
Thanks, your answer was perfect!



Il giorno 12-feb-2015, alle ore 18:15, Christian Smith <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Can you share some of the reasons you're thinking of using Mongo?

Theoretically it would be fairly easy to port. However, there is no current plan to do so. We don't believe Mongo is the right choice as the primary database for this project for a variety of reasons (ultimately Redis isn't the final answer either).

Philosophically, Anvil Connect is not an application. It's a piece of infrastructure that supports applications. In line with that reasoning, Anvil should take responsibility for persistence internally, using an embedded database like lmdb or leveldb.

The advantage of this approach is that there are no external dependencies. Deployment would be simpler and cheaper. The main disadvantage is that we have to deal with horizontal scalability of persistence in-house as well. For example, implementing dynamo or a similar pattern. This a longer term vision that many will argue is out of reach. I'm personally excited to make a branch and start experimenting as time permits.

Operational persistence aside, the data shouldn't be locked up in Anvil. One feature we've discussed is writing to multiple data stores simultaneously while reading only from the primary one. I can't be certain how difficult this would be in practice until we take a closer look.

Feedback and ideas are appreciated :)

-
