### ISSUE TITLE
Empty user name after normal registration.

### ISSUE THREAD

**Issue by ic-3pg** [christiansmith/anvil-connect#87]
After a normal registration (without social media) the userinfo does not contain the user name.

The config:
  "providers": {
    "password": true
  }

Is there a way to get back the user name after the registration?

**Comment by christiansmith** [comment]
Thanks for pointing this out. Looks like an issue with the field names in the signup form. We'll have a fix out shortly.

**Comment by christiansmith** [comment]
#88 fixes this. Merged.
